### ISSUE TITLE
SwiftBar v1.0.2 betas: Catalina reports

### ISSUE THREAD

**Issue by JayBrown** [swiftbar/SwiftBar#28]
Using this script: https://github.com/JayBrown/Ping-Thing

(1a) ⚠️ Default font size is still one point too small (see below
(1b) ⚠️ Menu items that should be greyed-out (read-only), are now black and selectable/clickable
(2) ⚠️ color inversion (black<>white) in menu on select not yet working

(3) ✅ hide SB icon works
(4) ✅ separators in sub-menus seem to work now
(5) ✅ "ghost menus" seem to be gone
(6) ✅ refresh together with bash seems to work now

v1.0.2-beta1

![snap1](https://i.imgur.com/Vn4ksam.png)

v1.0.1

![snap2](https://i.imgur.com/tgoN2QQ.png)

**Comment by melonamin** [comment]
>(1a) ⚠️ Default font size is still one point too small (see below
(1b) ⚠️ Menu items that should be greyed-out (read-only), are now black and selectable/clickable
(2) ⚠️ color inversion (black<>white) in menu on select not yet working

Addressed in the [new build](https://github.com/swiftbar/SwiftBar/releases/tag/1.0.2-beta-2), not sure about the font size - I can't reproduce it on my end, but I've made some changes.

**Comment by JayBrown** [comment]
Thank you. After a quick glance, everything seems to work now _except_ the font size issue. Maybe I should just upgrade to Big Sur. (Just kidding.)

![snap](https://i.imgur.com/yqN0VOA.png)

**Comment by JayBrown** [comment]
At first glance everything seems to work now _except_ the small font size, which is still an issue (on Catalina at least).

See also the crash report here: https://github.com/swiftbar/SwiftBar/issues/30

**Comment by melonamin** [comment]
This font thing is giving me a headache, in my Catalina tests font looks like it should, but I see that on your screenshot it is wrong, will keep digging.

**Comment by JayBrown** [comment]
I have set my 15'' MBP to a precise Retina*1 resolution, i.e. one setting below the weird default macOS resolution… maybe that's relevant.

![snap](https://i.imgur.com/t1TnU6R.jpg)

**Comment by melonamin** [comment]
This actually helped, thank you. I was testing on Catalina virtual machine and couldn't reproduce the bug, 15 inch with Catalina worked.

New [build](https://github.com/swiftbar/SwiftBar/releases/tag/1.0.2-beta-3)

**Comment by JayBrown** [comment]
Still giving me the 1pt-smaller font.

![snap](https://i.imgur.com/kgj2Fs9.png)

**Comment by melonamin** [comment]
Actually we're getting there, on this screenshot only "SwiftBar" is of a wrong size, "Run in Terminal" and bellow are the same as "Pause", "Refresh"...

**Comment by JayBrown** [comment]
However, we should keep in mind that "SwiftBar" has the correct size here (system default with 13 pt, I assume).

**Comment by melonamin** [comment]
This is not what I've found in my testing.

This is how I create all standard items in Swiftbar `NSMenuItem(title: "SwiftBar", action: nil, keyEquivalent: "")`, this results in 13pt in Big Sur and 14pt in Catalina(on MacBook, in VM it seems to be 13pt as well).

User defined menu items are created a bit differently, since title font, size and color can be user defined I'm using attributedTitle, `menuItem.attributedTitle = NSAttributedString(string: item.title, attributes: [.font:NSFont.menuFont(ofSize: 0)])`. Key part here is [NSFont.menuFont(ofSize: 0)](https://developer.apple.com/documentation/appkit/nsfont/1533068-menufont), which returns 13pt both on Catalina and Big Sur.

So in recent build I switched all menu items to using `attributedTitle` with explicit font instead of default `title` behavior, I forgot to change it for "SwiftBar" menu item and that's why it is bigger(at 14pt) than everything else.

**Comment by JayBrown** [comment]
Which is weird, though, because in application menus, as well as in BitBar and other menu bar apps, the font is always the same size as the "SwiftBar" string in the SwiftBar, and on my MBP with Catalina that seems to be the default system font size for menus. I can't say whether that's 13 or 14 points, but judging from what TinkerTool tells me, it should be 13 points. (But apparently it's not?)

**Comment by melonamin** [comment]
Ok, here is a test harness:

![Screen Shot 2020-11-28 at 5 05 02 PM](https://user-images.githubusercontent.com/222100/100526979-0e545880-319c-11eb-81bf-fb725f087435.jpeg)

So it looks like the first two are what we need here, and we should switch to [menuBarFont](https://developer.apple.com/documentation/appkit/nsfont/1534194-menubarfont) from menuFont

**Comment by JayBrown** [comment]
This has worked, at least on Catalina. Thank you! Hope everything's fine on Big Sur, too.

(Will re-open if I find other bugs with the v1.0.2 betas. But it seems great so far.)

![snap](https://i.imgur.com/m8QsDpD.png)
